version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.2.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.2.x)"
    milestone: 30
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.1.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.1.x)"
    milestone: 29
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.0.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.0.x)"
    milestone: 26
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "1.6.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(1.6.x)"
    milestone: 27
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "com.github.tomakehurst:wiremock-jre8-standalone"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "1.5.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(1.5.x)"
    milestone: 25
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "com.github.tomakehurst:wiremock-jre8-standalone"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
